{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codeborne",
    "module": "selenide",
    "version": "6.19.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "4.13.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "com.codeborne",
          "module": "selenide-core",
          "version": {
            "requires": "6.19.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.3"
          },
          "reason": "used by browserup-proxy"
        }
      ],
      "files": [
        {
          "name": "selenide-6.19.1.jar",
          "url": "selenide-6.19.1.jar",
          "size": 27176,
          "sha512": "d3c13af1c8a4a2efec712e50ea94e681e8b0c75e1b4feec485cb51bf25ec97363c92880f75acae000e5cda5a7eb542c69c3563f82d7606d99b6d341451f49191",
          "sha256": "2d0dece08a5b29f1af57b2e2924c207dfa498f4505a9ca3f8934920b2c3fa1dd",
          "sha1": "286edcfef9fbac630b75d8e0220c144e40e6d008",
          "md5": "cbcb7dbd381f90de5b7777c5eb9f5952"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.13.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.seleniumhq.selenium",
          "module": "selenium-java",
          "version": {
            "requires": "4.13.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "com.codeborne",
          "module": "selenide-core",
          "version": {
            "requires": "6.19.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.3"
          },
          "reason": "used by browserup-proxy"
        }
      ],
      "files": [
        {
          "name": "selenide-6.19.1.jar",
          "url": "selenide-6.19.1.jar",
          "size": 27176,
          "sha512": "d3c13af1c8a4a2efec712e50ea94e681e8b0c75e1b4feec485cb51bf25ec97363c92880f75acae000e5cda5a7eb542c69c3563f82d7606d99b6d341451f49191",
          "sha256": "2d0dece08a5b29f1af57b2e2924c207dfa498f4505a9ca3f8934920b2c3fa1dd",
          "sha1": "286edcfef9fbac630b75d8e0220c144e40e6d008",
          "md5": "cbcb7dbd381f90de5b7777c5eb9f5952"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "selenide-6.19.1-javadoc.jar",
          "url": "selenide-6.19.1-javadoc.jar",
          "size": 155044,
          "sha512": "c0841f9011c5f93ba3f31cb5a399a6ed87e7a95ca3e3641b2abc20c21753cc6db60ac9e7cb1bbfbf3cf095c568c8db2b03b4b48943c3084201c0fa9e20626a85",
          "sha256": "f2cae90433de5111f677133dd51853a59d876e717c7cd023f9cd2bedea9f8ad8",
          "sha1": "79fdc6a345948f6d3e1e4d57a49ea625398cf3e1",
          "md5": "cac32a5283075339fd1015c674fd50c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "selenide-6.19.1-sources.jar",
          "url": "selenide-6.19.1-sources.jar",
          "size": 24938,
          "sha512": "8d618cba121d8cc00797717cb7b17eb2e7fa1f0b9500e9ff7f40f558440ad7c37f44f5d88c82b385467db9e514e4138aab4583b3731e0a4dfff032eb4e1fee83",
          "sha256": "abc44829bd89456cb557d677b4c0acfada7a22bf3e5c23d22a5a1d30530110c7",
          "sha1": "ba787206290f81ebb76d25f94a9b9dc8888b08fa",
          "md5": "485779f61c4a60af8ee7b9eb891b47ea"
        }
      ]
    }
  ]
}
