{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter",
    "version": "5.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "5.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-5.9.0.jar",
          "url": "junit-jupiter-5.9.0.jar",
          "size": 6358,
          "sha512": "9d43be7b25d8851eff14c1a47308a449cec04c7edb28fe69ec2202d26f297814821d2d4a4051384e64a961aea3a8f3731b78dcb66ecfb53d61a6607d2701bb7f",
          "sha256": "2db2e4aa2b5e82fefcbf18d0af20c8095a43e94ad9ab9d16bd87557cdaa397dd",
          "sha1": "0db1cd1cd9e3138cf9e5ecb12a2ccc9cfbdf6a1d",
          "md5": "55f29774430fc46d164400985dfc45e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-5.9.0.jar",
          "url": "junit-jupiter-5.9.0.jar",
          "size": 6358,
          "sha512": "9d43be7b25d8851eff14c1a47308a449cec04c7edb28fe69ec2202d26f297814821d2d4a4051384e64a961aea3a8f3731b78dcb66ecfb53d61a6607d2701bb7f",
          "sha256": "2db2e4aa2b5e82fefcbf18d0af20c8095a43e94ad9ab9d16bd87557cdaa397dd",
          "sha1": "0db1cd1cd9e3138cf9e5ecb12a2ccc9cfbdf6a1d",
          "md5": "55f29774430fc46d164400985dfc45e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-5.9.0-javadoc.jar",
          "url": "junit-jupiter-5.9.0-javadoc.jar",
          "size": 5681,
          "sha512": "1fae01f45210a2a2a4f67b91eddda48f1d238140a97c49ec9f0d7311679ad4af48265273e5efcefa2f311ccf2e0653ccc76af9050f0807a8fded566d99178fea",
          "sha256": "87e2e56e44d1ce3a882eff2bed179ea74a27cbcbd888f13536c413a87d32f58a",
          "sha1": "3c791495768512669e0463f7be775c1ee4ea10c3",
          "md5": "6c7369516c034cf85e6adbce4a9ed291"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-5.9.0-sources.jar",
          "url": "junit-jupiter-5.9.0-sources.jar",
          "size": 6092,
          "sha512": "261e62db845b133ee533676255e3d4961911cd97dba8962e90b580d6fc87b4c813956d50d688341a4e603d3463db0f340e9c440b573222b98a80350821029cd6",
          "sha256": "2d0cfc6150ce624fe19b039a483ef0a0ba54620916282b0e35ea78f7626abb50",
          "sha1": "5fd01c33132462aab3905cb74bd1097a713ab91a",
          "md5": "fb39489b11df433439ec53e5bf32ee12"
        }
      ]
    }
  ]
}
